/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletos;

import boletos.controllers.BoletosController;
import static Ferramentas.InternalFrame.GFrame.startCursor;
import static Ferramentas.InternalFrame.GFrame.stopCursor;
import Ferramentas.Managers.Managers;
import Ferramentas.Mensagem.Mensagem;
import Ferramentas.TableModel.TbModelReflection;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.commons.lang3.StringUtils;
import principal.models.TbBoletosGerados;

/**
 *
 * @author ANDRE PORTO
 */
public class BoletosPendentes extends javax.swing.JInternalFrame {

    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

    EntityManager em = Managers.GetManager();
    TbModelReflection mdPendentes;
    List<TbBoletosGerados> lPendentes;
    Calendar dtVencidos = Calendar.getInstance();
    Calendar dtFinal = Calendar.getInstance();
    Calendar dtInicial = Calendar.getInstance();

    /**
     * Creates new form BoletosPendentes
     */
    public BoletosPendentes() {
        initComponents();
        setTitle("Boletos Pendentes");
        mdPendentes = new TbModelReflection<TbBoletosGerados>() {
            {
                setName(jTable1, "competencia", "dtProcessado", "dsCliente", "nrCpfCnpj14", "dsMunicipio", "dsUf", "dtVencimento", "vlBoleto", "Gerar");
                setModel("competencia", "dtProcessado", "contratoId.clienteId.dsCliente", "contratoId.clienteId.nrCpfCnpj14", "contratoId.clienteId.dsMunicipio", "contratoId.clienteId.dsUf", "dtVencimento", "vlBoleto", "inGerarBoleto");
                setPreferredWidth(50, 50, 200, 100, 150, 10, 50, 50, 10);
                setEditableAt(8);
            }
        };

        dtInicial.add(Calendar.MONTH, -2);
        dtFinal.add(Calendar.MONTH, +2);
        tfDtFim.setDate(dtFinal.getTime());
        tfDtIni.setDate(dtInicial.getTime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        tfDtVencimento = new Ferramentas.Datas.DateField();
        jLabel4 = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        btGerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDtIni = new Ferramentas.Datas.DateField();
        tfDtFim = new Ferramentas.Datas.DateField();
        btBuscar = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox();

        jLabel4.setText("Data Vencimento:");

        btCancelar.setText("Cancelar");

        btGerar.setText("Gerar");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelar)
                    .addComponent(btGerar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setClosable(true);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        jLabel3.setText("Status:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "ATIVOS", "VENCIDOS" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDtIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfDtIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscar)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        lPendentes = em.createQuery("SELECT t FROM TbBoletosGerados t where t.in2Via=?1 and t.dtVencimento BETWEEN ?2 and ?3 and t.dtPagamento is null").setParameter(1, false).setParameter(2, tfDtIni.getDate()).setParameter(3, tfDtFim.getDate()).getResultList();
        mdPendentes.setList(lPendentes);

    }//GEN-LAST:event_btBuscarActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() > -1 && jTable1.getSelectedColumn() == 8) {
            jDialog1.setBounds(0, 0, 280, 150);
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
            boletoVencido = lPendentes.get(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()));
        }

    }//GEN-LAST:event_jTable1MouseReleased

    TbBoletosGerados boletoVencido;

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (file.showDialog(file, "Gerar") == 0) {
            new Thread() {

                @Override
                public void run() {
                    startCursor(rootPane);
                    File files = file.getSelectedFile();
                    TbBoletosGerados boleto;
                    boleto = new TbBoletosGerados();
                    boleto.setContratoId(boletoVencido.getContratoId());
                    boleto.setInEnviadoRemessa(false);
                    boleto.setDtProcessado(new Date());
                    boleto.setDtVencimento(tfDtVencimento.getDate());
                    boleto.setCompetencia(boletoVencido.getCompetencia());
                    boleto.setIn2Via(false);
                    em.persist(boleto);
                    em.getTransaction().begin();
                    em.getTransaction().commit();

                    boleto.setVlBoleto(boletoVencido.getVlBoleto());
                    boleto.setNrNossoNumero(StringUtils.leftPad(boleto.getId().toString(), 8, "0"));
                   // boleto.setCdDac(BoletosController.GerarDac("023683420109" + boleto.getNrNossoNumero()));
                    boletoVencido.setIn2Via(true);

                    em.merge(boletoVencido);
                    em.merge(boleto);
                    BoletosController.gerar(boleto, files);

                    em.getTransaction().begin();
                    em.getTransaction().commit();
                    jDialog1.dispose();
                    stopCursor(rootPane);
                    Mensagem.show(Mensagem.GERAR_BOLETOS);

                }

            }.start();

        }

    }//GEN-LAST:event_btGerarActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
        if (cbStatus.getSelectedIndex() == 0) {
            filtrarJTable(null, 0);
        } else if (cbStatus.getSelectedIndex() == 1) {
            filtrarJTable(dtVencidos.getTime(), 1);
        } else if (cbStatus.getSelectedIndex() == 2) {
            filtrarJTable(dtVencidos.getTime(), 2);

        }
    }//GEN-LAST:event_cbStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGerar;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private Ferramentas.Datas.DateField tfDtFim;
    private Ferramentas.Datas.DateField tfDtIni;
    private Ferramentas.Datas.DateField tfDtVencimento;
    // End of variables declaration//GEN-END:variables

    void filtrarJTable(Date data, int vencidos) {
        TableModel tbModel = jTable1.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbModel);
        List<RowFilter<TableModel, Object>> listFiltros = new ArrayList<>();
        RowFilter<TableModel, Object> compoundRowFilter = null;
        sorter.setRowFilter(compoundRowFilter);
        if (vencidos == 1) {
            listFiltros.add(RowFilter.dateFilter(RowFilter.ComparisonType.AFTER, data, 6));
        } else if (vencidos == 2) {
            listFiltros.add(RowFilter.dateFilter(RowFilter.ComparisonType.BEFORE, data, 6));
        } else {
            listFiltros.add(RowFilter.regexFilter("(?i)", 6));
        }

        jTable1.setRowSorter(sorter);
        compoundRowFilter = RowFilter.andFilter(listFiltros);
        sorter.setRowFilter(compoundRowFilter);
    }

}
