/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import Ferramentas.InternalFrame.GFrame;
import Ferramentas.Managers.Managers;
import Ferramentas.Mensagem.Mensagem;
import Ferramentas.TableModel.TbModelReflection;
import java.awt.Point;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.DefaultComboBoxModel;

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.MaskFormatter;
import javax.swing.text.PlainDocument;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import principal.models.TbClienteContatos;
import principal.models.TbClienteContratos;
import principal.models.TbClientes;
import principal.models.TbTipoBoletos;
import principal.models.TbTipoContatos;

/**
 *
 * @author ANDRE PORTO
 */
public class CadastrarClientesBoleto extends GFrame {

    EntityManager em = Managers.GetManager();
    TbClientes cliente;
    List<TbClienteContatos> lContato = new ArrayList();
    List<TbClienteContratos> lContrato = new ArrayList();
    TbModelReflection mdContato;
    TbModelReflection mdContrato;
    TbClienteContatos contato;
    TbClienteContratos contrato;
    int rowContato;
    int rowContrato;

    /**
     * Creates new form CadastrarClientesBoleto
     */
    public CadastrarClientesBoleto() {
        initComponents();
        cliente = new TbClientes();
        em.persist(cliente);
        inicio();

    }

    public CadastrarClientesBoleto(TbClientes cli) {
        initComponents();
        cliente = cli;
        inicio();
        lContato = em.createQuery("SELECT t FROM TbClienteContatos t WHERE t.clienteId=?1").setParameter(1, cli).getResultList();
        mdContato.setList(lContato);
        lContrato = em.createQuery("SELECT t FROM TbClienteContratos t WHERE t.clienteId=?1").setParameter(1, cli).getResultList();
        mdContrato.setList(lContrato);

        tfBairro.setText(cliente.getDsBairro());
        tfCep.setText(cliente.getDsCep());
        tfCliente.setText(cliente.getDsCliente());
        tfCpfCnpj.setText(cliente.getNrCpfCnpj14());
        tfLogradouro.setText(cliente.getDsLogradouro());
        tfMunicipio.setText(cliente.getDsMunicipio());
        cbUf.setSelectedItem(cliente.getDsUf());
        tfDtContrado.setDate(cliente.getDtContrato());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmContato = new javax.swing.JPopupMenu();
        miExcluirContato = new javax.swing.JMenuItem();
        pmContrato = new javax.swing.JPopupMenu();
        miExcluirContrato = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        tfMunicipio = new javax.swing.JTextField();
        tfCep = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        tfCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDtContrado = new Ferramentas.Datas.DateField();
        cbUf = new javax.swing.JComboBox();
        tfCpfCnpj = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfDsContato = new javax.swing.JTextField();
        btIncluirContato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContato = new javax.swing.JTable();
        cbTpContato = new javax.swing.JComboBox();
        btSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbTpContrato = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfDtInicial = new Ferramentas.Datas.DateField();
        tfDtFinal = new Ferramentas.Datas.DateField();
        tfValor = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        tfDiaVencimento = new javax.swing.JTextField();
        btIncluirMensalidade = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbContrato = new javax.swing.JTable();

        miExcluirContato.setText("Excluir");
        miExcluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirContatoActionPerformed(evt);
            }
        });
        pmContato.add(miExcluirContato);

        miExcluirContrato.setText("Excluir");
        miExcluirContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirContratoActionPerformed(evt);
            }
        });
        pmContrato.add(miExcluirContrato);

        setClosable(true);
        setTitle("Cadastro de Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("UF:");

        jLabel8.setText("CEP:");

        tfBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBairroKeyReleased(evt);
            }
        });

        tfMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMunicipioKeyReleased(evt);
            }
        });

        jLabel1.setText("Nome Cliente:");

        tfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClienteKeyReleased(evt);
            }
        });

        jLabel2.setText("CPF\\CNPJ:");

        jLabel3.setText("Logradouro:");

        tfLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLogradouroKeyReleased(evt);
            }
        });

        jLabel4.setText("Data Contrato:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("Município:");

        tfCpfCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCpfCnpjKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDtContrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(tfCpfCnpj)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfDtContrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Contatos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel9.setText("Tipo Contato:");

        jLabel10.setText("Informação:");

        btIncluirContato.setText("Incluir");
        btIncluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirContatoActionPerformed(evt);
            }
        });

        tbContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbContato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbContatoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbContato);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(cbTpContato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDsContato, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btIncluirContato)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(tfDsContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIncluirContato)
                    .addComponent(cbTpContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Cobrança", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel11.setText("Data Inicial:");

        jLabel12.setText("Data Final:");

        jLabel13.setText("Valor:");

        jLabel14.setText("Tipo:");

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        tfValor.setToolTipText("");
        tfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorKeyTyped(evt);
            }
        });

        jLabel15.setText("Dia Vencimento:");

        jLabel16.setText("Descrição:");

        tfDiaVencimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDiaVencimentoKeyTyped(evt);
            }
        });

        btIncluirMensalidade.setText("Incluir");
        btIncluirMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirMensalidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbTpContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDiaVencimento))
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btIncluirMensalidade)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbTpContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(tfDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIncluirMensalidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbContratoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbContrato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvar))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (!isValidCnpj(tfCpfCnpj.getText().replaceAll("[^0-9]", ""))) {
       Mensagem.show(Mensagem.CNPJ_INVALIDO);

            tfCpfCnpj.grabFocus();
            return;
        }

        Long qt = (Long) em.createNativeQuery("SELECT COUNT(NR_CPF_CNPJ14) FROM TB_CLIENTES WHERE NR_CPF_CNPJ14=?1").setParameter(1, tfCpfCnpj.getText().replaceAll("[^0-9]", "")).getSingleResult();
        if (qt != 0) {
            if (cliente.getNrCpfCnpj14() == null || !cliente.getNrCpfCnpj14().equals(tfCpfCnpj.getText().replaceAll("[^0-9]", ""))) {
                  Mensagem.show(Mensagem.CNPJ_CADASTRADO);

                tfCpfCnpj.grabFocus();
                return;
            }
        }

        cliente.setDsBairro(tfBairro.getText());
        cliente.setDsCep(tfCep.getText().replaceAll("[^0-9]", ""));
        cliente.setDsCliente(tfCliente.getText());
        cliente.setDsLogradouro(tfLogradouro.getText());
        cliente.setDsMunicipio(tfMunicipio.getText());
        cliente.setDsUf(cbUf.getSelectedItem().toString());
        cliente.setNrCpfCnpj14(tfCpfCnpj.getText().replaceAll("[^0-9]", ""));
        cliente.setDtContrato(tfDtContrado.getDate());
        em.merge(cliente);
        em.getTransaction().begin();
        em.getTransaction().commit();
        Mensagem.show(Mensagem.SALVAR);
        cleanFields(rootPane);
        cliente = new TbClientes();
        em.persist(cliente);
        lContato.clear();
        lContrato.clear();
        mdContato.setList(lContato);
        mdContrato.setList(lContrato);
        tfValor.setText("0,00");

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btIncluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirContatoActionPerformed
        // TODO add your handling code here:
        Boolean novo;
        if (novo = contato == null) {
            contato = new TbClienteContatos();
        }
        contato.setClienteId(cliente);
        contato.setDsContato(tfDsContato.getText());
        contato.setTpContatoId((TbTipoContatos) cbTpContato.getSelectedItem());
        contato.setInStatus(true);
        if (novo) {
            em.persist(contato);
            lContato.add(contato);
        } else {
            em.merge(contato);
        }
        mdContato.setList(lContato);
        tfDsContato.setText(null);
        contato = null;
    }//GEN-LAST:event_btIncluirContatoActionPerformed

    private void btIncluirMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirMensalidadeActionPerformed
        // TODO add your handling code here:
        Boolean novo;
        if (novo = contrato == null) {
            contrato = new TbClienteContratos();

        }
        contrato.setClienteId(cliente);
        contrato.setDiaVencimento(tfDiaVencimento.getText());
        contrato.setDtFinal(tfDtFinal.getDate());
        contrato.setDtInicial(tfDtInicial.getDate());
        contrato.setVlBoleto(new BigDecimal(tfValor.getText().replaceAll("[.]", "").replace(",", ".")));
        contrato.setTipoBoletoId((TbTipoBoletos) cbTpContrato.getSelectedItem());
        contrato.setDsDescricao(tfDescricao.getText());
        if (novo) {
            em.persist(contrato);
            lContrato.add(contrato);
        } else {
            em.merge(contrato);
        }
        mdContrato.setList(lContrato);
        tfDiaVencimento.setText(null);
        tfDtInicial.setDate(null);
        tfDtFinal.setDate(null);
        tfValor.setText("0,00");
        tfDescricao.setText(null);
        contrato = null;

    }//GEN-LAST:event_btIncluirMensalidadeActionPerformed

    private void tfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyReleased
        // TODO add your handling code here:
        fixarLength(evt, tfCliente, 40, false);
    }//GEN-LAST:event_tfClienteKeyReleased

    private void tfLogradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLogradouroKeyReleased
        // TODO add your handling code here:
        fixarLength(evt, tfLogradouro, 40, false);
    }//GEN-LAST:event_tfLogradouroKeyReleased

    private void tfBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBairroKeyReleased
        // TODO add your handling code here:
        fixarLength(evt, tfBairro, 12, false);
    }//GEN-LAST:event_tfBairroKeyReleased

    private void tfMunicipioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMunicipioKeyReleased
        // TODO add your handling code here:
        fixarLength(evt, tfMunicipio, 15, false);
    }//GEN-LAST:event_tfMunicipioKeyReleased

    private void tfCpfCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCpfCnpjKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfCnpjKeyReleased

    private void tbContatoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContatoMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            contato = lContato.get(tbContato.convertRowIndexToModel(tbContato.getSelectedRow()));
            cbTpContato.setSelectedItem(contato.getTpContatoId());
            tfDsContato.setText(contato.getDsContato());
        }
        if (tbContato.isEnabled() && evt.isPopupTrigger()) {
            Point p = new Point(evt.getX(), evt.getY());
            rowContato = tbContato.rowAtPoint(p);
            pmContato.show(tbContato, p.x, p.y);
        }
    }//GEN-LAST:event_tbContatoMouseReleased

    private void miExcluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirContatoActionPerformed
        // TODO add your handling code here:
        contato = lContato.get(tbContato.convertRowIndexToModel(rowContato));
        em.remove(contato);
        lContato.remove(contato);
        mdContato.setList(lContato);

    }//GEN-LAST:event_miExcluirContatoActionPerformed

    private void miExcluirContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirContratoActionPerformed
        // TODO add your handling code here:
        contrato = lContrato.get(tbContrato.convertRowIndexToModel(rowContrato));
        em.remove(contrato);
        lContrato.remove(contrato);
        mdContrato.setList(lContrato);
    }//GEN-LAST:event_miExcluirContratoActionPerformed

    private void tbContratoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContratoMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            contrato = lContrato.get(tbContrato.convertRowIndexToModel(tbContrato.getSelectedRow()));
            tfDtFinal.setDate(contrato.getDtFinal());
            tfDtInicial.setDate(contrato.getDtInicial());
            tfValor.setText(formatarValores(contrato.getVlBoleto()));
            cbTpContrato.setSelectedItem(contrato.getTipoBoletoId());
            tfDescricao.setText(contrato.getDsDescricao());
            tfDiaVencimento.setText(contrato.getDiaVencimento());

        }
        if (tbContrato.isEnabled() && evt.isPopupTrigger()) {
            Point p = new Point(evt.getX(), evt.getY());
            rowContrato = tbContrato.rowAtPoint(p);
            pmContrato.show(tbContrato, p.x, p.y);
        }
    }//GEN-LAST:event_tbContratoMouseReleased

    private void tfValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorKeyTyped
        // TODO add your handling code here:
        KeyDouble(evt, ',', false);
    }//GEN-LAST:event_tfValorKeyTyped

    private void tfDiaVencimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiaVencimentoKeyTyped
        // TODO add your handling code here:
        KeyDouble(evt, '0', false);
    }//GEN-LAST:event_tfDiaVencimentoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluirContato;
    private javax.swing.JButton btIncluirMensalidade;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbTpContato;
    private javax.swing.JComboBox cbTpContrato;
    private javax.swing.JComboBox cbUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem miExcluirContato;
    private javax.swing.JMenuItem miExcluirContrato;
    private javax.swing.JPopupMenu pmContato;
    private javax.swing.JPopupMenu pmContrato;
    private javax.swing.JTable tbContato;
    private javax.swing.JTable tbContrato;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfCpfCnpj;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfDiaVencimento;
    private javax.swing.JTextField tfDsContato;
    private Ferramentas.Datas.DateField tfDtContrado;
    private Ferramentas.Datas.DateField tfDtFinal;
    private Ferramentas.Datas.DateField tfDtInicial;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfMunicipio;
    private javax.swing.JFormattedTextField tfValor;
    // End of variables declaration//GEN-END:variables

    public class Maiusculo_Minusculo extends PlainDocument {

        Boolean maiusculo;

        public Maiusculo_Minusculo(Boolean opcao) {
            super();
            maiusculo = opcao;
        }

        @Override
        public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
            if (str == null) {
                return;
            }

            str = str.replaceAll("[^a-zA-Z0-9 ,.]", "");

            if (maiusculo) {
                super.insertString(offs, str.toUpperCase(), a);
            } else {
                super.insertString(offs, str.toLowerCase(), a);
            }
            //super.insertString(offs, unaccented, a);
        }
    }

    private void inicio() {
        mdContato = new TbModelReflection<TbClienteContatos>() {
            {
                setName(tbContato, "Tipo de contato", "Informação");
                setModel("tpContatoId", "dsContato");
            }
        };
        mdContrato = new TbModelReflection<TbClienteContratos>() {
            {
                setName(tbContrato, "dt inicial", "dt final", "dia vencimento", "valor", "tipo boleto");
                setModel("dtInicial", "dtFinal", "diaVencimento", "vlBoleto", "tipoBoletoId");
            }
        };
        cbTpContrato.setModel(new DefaultComboBoxModel(em.createQuery("SELECT t FROM TbTipoBoletos t order by t.dsTipoBoleto").getResultList().toArray()));
        cbTpContato.setModel(new DefaultComboBoxModel(em.createQuery("SELECT t FROM TbTipoContatos t order by t.dsTipoContato").getResultList().toArray()));
        tfCliente.setDocument(new Maiusculo_Minusculo(true));
        tfLogradouro.setDocument(new Maiusculo_Minusculo(true));
        tfMunicipio.setDocument(new Maiusculo_Minusculo(true));
        tfBairro.setDocument(new Maiusculo_Minusculo(true));

        List ufs = getUf();
        ufs.remove(0);
        cbUf.setModel(new DefaultComboBoxModel(ufs.toArray()));
        AutoCompleteDecorator.decorate(cbUf);

        try {
            MaskFormatter mask;
            mask = new MaskFormatter("#####-###");
            mask.setPlaceholderCharacter('_');
            mask.install(tfCep);
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarClientesBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfValor.setText("0,00");
        formataCpfCnpj(tfCpfCnpj);
    }

    public static boolean isValidCnpj(final String cnpj) {
        String value = cnpj.trim();
        if (value.length() < 14) {
            value = leftPad(value, 14, "0");
        } else if (value.length() > 14) {
            return false;
        }

        try {
            if (!value.equals("00000000000000")) {
                int sum = 0, digit = 0;
                String calc = value.substring(0, 12);
                char[] chrvalue = value.toCharArray();

                //Parte 1
                for (int i = 0; i < 4; i++) {
                    if (chrvalue[i] - 48 >= 0 && chrvalue[i] - 48 <= 9) {
                        sum += (chrvalue[i] - 48) * (6 - (i + 1));
                    }
                }

                for (int i = 0; i < 8; i++) {
                    if (chrvalue[i + 4] - 48 >= 0 && chrvalue[i + 4] - 48 <= 9) {
                        sum += (chrvalue[i + 4] - 48) * (10 - (i + 1));
                    }
                }

                digit = 11 - (sum % 11);
                calc += (digit == 10 || digit == 11) ? "0" : Integer.toString(digit);

                //Parte 2
                sum = 0;
                for (int i = 0; i < 5; i++) {
                    if (chrvalue[i] - 48 >= 0 && chrvalue[i] - 48 <= 9) {
                        sum += (chrvalue[i] - 48) * (7 - (i + 1));
                    }
                }

                for (int i = 0; i < 8; i++) {
                    if (chrvalue[i + 5] - 48 >= 0 && chrvalue[i + 5] - 48 <= 9) {
                        sum += (chrvalue[i + 5] - 48) * (10 - (i + 1));
                    }
                }

                digit = 11 - (sum % 11);
                calc += (digit == 10 || digit == 11) ? "0" : Integer.toString(digit);
                return value.equals(calc);
            }
            return false;
        } catch (Exception e) {
            return false;
        }
    }

    public static String leftPad(String value, int size, String pad) {

        if (value.length() < size && !pad.isEmpty()) {
            return leftPad(pad.concat(value), size, pad);
        }
        return value;
    }

}
