/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JProgressBar;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ANDRE PORTO
 */
public class Login extends javax.swing.JFrame {

    private JProgressBar barDo;

    public Login() {
        //  setContentPane(new JDesktopPaneComImagem("/imagens/icone.png"));
        setContentPane(new JDesktopPaneComImagem("/imagens/icone.png"));
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/imagens/icone.png")));
        initComponents();
        msgLabel.setText("Usuário ou senha inválidos. Tente novamente");
        msgLabel.setVisible(false);
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("/imagens/icone.png")));

        tfNick.grabFocus();
        loading.setVisible(false);
    }

    public class JDesktopPaneComImagem extends JDesktopPane {

        private static final long serialVersionUID = 1L;
        Image imagem;

        public JDesktopPaneComImagem(String caminho) {
            imagem = Toolkit.getDefaultToolkit().createImage(getClass().getResource(caminho));
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagem != null) {
                g.drawImage(imagem, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsNickLabel = new javax.swing.JLabel();
        tfNick = new javax.swing.JTextField();
        dsSenhaLabel = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        loading = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(431, 353));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        dsNickLabel.setLabelFor(tfNick);
        dsNickLabel.setText("Usuário:");
        dsNickLabel.setPreferredSize(new java.awt.Dimension(80, 16));

        tfNick.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNick.setText("virtual");
        tfNick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNickKeyPressed(evt);
            }
        });

        dsSenhaLabel.setLabelFor(tfSenha);
        dsSenhaLabel.setText("Senha:");
        dsSenhaLabel.setPreferredSize(new java.awt.Dimension(80, 16));

        tfSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSenha.setText("V2016");
        tfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSenhaKeyPressed(evt);
            }
        });

        btLogin.setText("Entrar");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 51, 51));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLabel.setText("Usuário ou senha inválidos. Tente novamente");

        org.jdesktop.layout.GroupLayout loadingLayout = new org.jdesktop.layout.GroupLayout(loading);
        loading.setLayout(loadingLayout);
        loadingLayout.setHorizontalGroup(
            loadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        loadingLayout.setVerticalGroup(
            loadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(68, 68, 68)
                .add(dsNickLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(tfNick, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(68, 68, 68)
                .add(dsSenhaLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(tfSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(174, 174, 174)
                .add(btLogin)
                .add(10, 10, 10)
                .add(sairButton))
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(msgLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 378, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(loading, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(174, 174, 174)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(dsNickLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(tfNick, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(dsSenhaLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(tfSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btLogin)
                    .add(sairButton))
                .add(6, 6, 6)
                .add(msgLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(loading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        new Login.LoginUsuario(tfNick.getText(), tfSenha.getPassword()).start();
        btLogin.setEnabled(false);
    }//GEN-LAST:event_btLoginActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        //   this.dispose();//     this.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    private void tfNickKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNickKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfSenha.grabFocus();
        }
        msgLabel.setVisible(false);
    }//GEN-LAST:event_tfNickKeyPressed

    private void tfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btLogin.grabFocus();
            btLogin.doClick();
        }
    }//GEN-LAST:event_tfSenhaKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            javax.swing.UIManager.setLookAndFeel(new javax.swing.plaf.nimbus.NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        Color cor = new Color(63, 169, 254);
        javax.swing.UIManager.put("nimbusOrange", cor);

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login log = new Login();
                log.setLocationRelativeTo(null);
                log.setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel dsNickLabel;
    private javax.swing.JLabel dsSenhaLabel;
    private javax.swing.JPanel loading;
    public static javax.swing.JLabel msgLabel;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField tfNick;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables

    private class LoginUsuario extends Thread {

        private String nmusuario;
        private String senha;

        public LoginUsuario(String nmUsuario, char[] password) {
            super("Login");
            this.nmusuario = nmUsuario;
            this.senha = new String(password);
        }

        @Override
        public void run() {
            loading.setVisible(true);
            try {
                msgLabel.setVisible(false);
                barDo = new JProgressBar();
                barDo.setVisible(true);
                barDo.setBounds(0, 0, 450, 20);
                loading.add(barDo);
                barDo.setString("Processando, aguarde.");
                barDo.setStringPainted(true);
                barDo.setIndeterminate(true);

                if (tfNick.getText().toUpperCase().equals("VIRTUAL") && new String(tfSenha.getPassword()).toUpperCase().equals("V2016")) {
                    Principal main = new Principal();
                    main.setVisible(true);
                    main.requestFocus();
                    dispose();
                } else {
                    barDo.setVisible(false);
                    msgLabel.setForeground(Color.red);
                    msgLabel.setVisible(true);
                    tfNick.requestFocus();
                    loading.setVisible(false);
                    btLogin.setEnabled(true);
                }

                //finaliza a barra
                barDo.setVisible(false);
                loading.setVisible(false);

            } catch (Exception e) {
                btLogin.setEnabled(true);

            }

        }
    }
}
